# Matrices

#### *variationalform* <https://variationalform.github.io/>

#### *Just Enough: progress at pace*

<https://variationalform.github.io/>

<https://github.com/variationalform>

Simon Shaw
<https://www.brunel.ac.uk/people/simon-shaw>.


<table>
<tr>
<td>
<img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" style="height:18px"/>
<img src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" style="height:18px"/>
<img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" style="height:18px"/>
</td>
<td>

<p>
This work is licensed under CC BY-SA 4.0 (Attribution-ShareAlike 4.0 International)

<p>
Visit <a href="http://creativecommons.org/licenses/by-sa/4.0/">http://creativecommons.org/licenses/by-sa/4.0/</a> to see the terms.
</td>
</tr>
</table>

<table>
<tr>
<td>This document uses</td>
<td>
<img src="https://www.python.org/static/community_logos/python-logo-master-v3-TM.png" style="height:30px"/>
</td>
<td>and also makes use of LaTeX </td>
<td>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/LaTeX_logo.svg/320px-LaTeX_logo.svg.png" style="height:30px"/>
</td>
<td>in Markdown</td> 
<td>
<img src="https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png" style="height:30px"/>
</td>
</tr>
</table>

## What this is about:

You will be introduced to ...

- Matrices as a way to represent tables of numbers.
- Matrices as a way to *operate* on vectors (and other matrices)
- The arithmetic (adding and subtracting) of matrices.
- The `numpy` library (or package) for working with matrices in `python`

We'll then look at special types of matrices, and derived quantities.

As usual our emphasis will be on *doing* rather than *proving*:
*just enough: progress at pace*


## Assigned Reading

For this worksheet you should read Chapters 6 and 7 of [VMLS] for more
introductory material on matrices, and also Appendix D of [DSML]
if you want to read more about `python` and `numpy`. 

- VMLS: Introduction to Applied Linear Algebra - Vectors, Matrices, and Least Squares,
  by Stephen Boyd and Lieven Vandenberghe,
  <https://web.stanford.edu/~boyd/vmls/>
- DSML: Data Science and Machine Learning, Mathematical and Statistical Methods
  by Dirk P. Kroese, Zdravko I. Botev, Thomas Taimre, Radislav Vaisman,
  <https://people.smp.uq.edu.au/DirkKroese/DSML> and
  <https://people.smp.uq.edu.au/DirkKroese/DSML/DSML.pdf>

Further accessible material can be found in [FCLA], and
advanced material is available in Chapters 2, 3 and 4 of [MML].

- MML: Mathematics for Machine Learning, by Marc Peter Deisenroth, A. Aldo Faisal, and Cheng Soon Ong.
  Cambridge University Press. <https://mml-book.github.io>.
- FCLA: A First Course in Linear Algebra, by Ken Kuttler, 
  <https://math.libretexts.org/Bookshelves/Linear_Algebra/A_First_Course_in_Linear_Algebra_(Kuttler)>
 
All of the above can be accessed legally and without cost.

There are also these useful references for coding:

- PT: `python`: <https://docs.python.org/3/tutorial>
- NP: `numpy`: <https://numpy.org/doc/stable/user/quickstart.html>
- MPL: `matplotlib`: <https://matplotlib.org>


## Matrices

A *matrix* is an $n$-row by $m$-column table of numbers enclosed in
brackets. For example,

$$
\boldsymbol{B} = \left(\begin{array}{rrr}
3 & 1 & -6.2 \\
2 & -5 & \pi
\end{array}\right),
\qquad
\boldsymbol{N} = \left(\begin{array}{rr}
-4 & 9 \\
7/8 & 6 \\
0 & 0
\end{array}\right),
\qquad
\boldsymbol{Z} = \left(\begin{array}{rrr}
1 &  2 & 0 \\
1 & -2 & 1 \\
0 &  1 & -4
\end{array}\right),
$$

are, in turn, a $2$ by $3$, a $3$ by $2$ and a $3$ by $3$ matrix. these
are called the matrix *shape*, or *dimension*.

Matrices are usually denoted by **bold** CAPITAL letters, and when $n=m$
we call the matrix *square*. For a square $n\times n$ matrix we will
just use $n$ as its dimension. So $\boldsymbol{Z}$ is square of
dimension $3$.

If we exchange the rows and columns of a matrix we get its *transpose*,
denoted with a superscript $T$ like so,

$$
\boldsymbol{B}^T = \left(\begin{array}{rr}
3    &  2 \\
1    & -5 \\
-6.2 & \pi
\end{array}\right),
\qquad
\boldsymbol{N}^T = \left(\begin{array}{rrr}
-4 & \frac{7}{8} & 0 \\
 9  & 6 & 0
\end{array}\right),
\qquad
\boldsymbol{Z}^T = \left(\begin{array}{rrr}
1 &  1 & 0 \\
2 & -2 & 1 \\
0 &  1 & -4
\end{array}\right).
$$


## Using `numpy` to represent matrices

As we have seen, `numpy` is a key tool for scientific computing
in `python`. See <https://numpy.org>

As before, we load in the numpy package and abbreviate it with `np`.

In [1]:
import numpy as np

Now we can set up the matrices above as `numpy` *arrays*, and print them out, as follows,

In [2]:
B = np.array([ [3,1, -6.2], [2,-5,np.pi] ])
N = np.array([ [-4, 9],[7/8, 6],[0, 0 ] ])
Z = np.array([ [1,2, 0],[1, -2, 1],[0, 1, -4] ])
print('B = \n', B)
print('N = \n', N)
print('Z = \n', Z)

B = 
 [[ 3.          1.         -6.2       ]
 [ 2.         -5.          3.14159265]]
N = 
 [[-4.     9.   ]
 [ 0.875  6.   ]
 [ 0.     0.   ]]
Z = 
 [[ 1  2  0]
 [ 1 -2  1]
 [ 0  1 -4]]


The matrix transpose just requires `.T` - like this

In [3]:
print('B.T = \n', B.T)
print('N.T = \n', N.T)
print('Z.T = \n', Z.T)

B.T = 
 [[ 3.          2.        ]
 [ 1.         -5.        ]
 [-6.2         3.14159265]]
N.T = 
 [[-4.     0.875  0.   ]
 [ 9.     6.     0.   ]]
Z.T = 
 [[ 1  1  0]
 [ 2 -2  1]
 [ 0  1 -4]]


These agree with what we had earlier,

$$
\boldsymbol{B}^T = \left(\begin{array}{rr}
3    &  2 \\
1    & -5 \\
-6.2 & \pi
\end{array}\right),
\qquad
\boldsymbol{N}^T = \left(\begin{array}{rrr}
-4 & \frac{7}{8} & 0 \\
 9  & 6 & 0
\end{array}\right),
\qquad
\boldsymbol{Z}^T = \left(\begin{array}{rrr}
1 &  1 & 0 \\
2 & -2 & 1 \\
0 &  1 & -4
\end{array}\right).
$$



## Addition and Subtraction

Matrices of the same dimension, or *shape,* can be added or subtracted
as in,

$$
\boldsymbol{B}-\boldsymbol{N}^T =  
\left(\begin{array}{rrr}
3 & 1 & -6.2 \\
2 & -5 & \pi
\end{array}\right)
-
\left(\begin{array}{rrr}
-4 & \frac{7}{8} & 0 \\
 9  & 6 & 0
\end{array}\right)
=
\left(\begin{array}{rrr}
 7 & \frac{1}{8} & -6.2 \\
-7& -11 & \pi
\end{array}\right)
$$

and

$$
\boldsymbol{Y}=\boldsymbol{Z}+\boldsymbol{Z}^T =
\left(\begin{array}{rrr}
1 &  2 & 0 \\
1 & -2 & 1 \\
0 &  1 & -4
\end{array}\right)
+
\left(\begin{array}{rrr}
1 &  1 & 0 \\
2 & -2 & 1 \\
0 &  1 & -4
\end{array}\right)
=
\left(\begin{array}{rrr}
2 &  3 & 0 \\
3 & -4 & 2 \\
0 &  2 & -8
\end{array}\right)
$$

This can be done in `numpy` exactly as expected...

In [4]:
print('B-N.T = \n', B-N.T)
Y = Z+Z.T
print('Y = \n', Y)

B-N.T = 
 [[  7.           0.125       -6.2       ]
 [ -7.         -11.           3.14159265]]
Y = 
 [[ 2  3  0]
 [ 3 -4  2]
 [ 0  2 -8]]


## Symmetry

Notice that $\boldsymbol{Y}=\boldsymbol{Y}^T$. 
This means for example that
$\boldsymbol{Y}-\boldsymbol{Y}^T=\boldsymbol{0}$ - the zero matrix.

In [5]:
print('Y = \n', Y)
print('Y.T = \n', Y.T)
print('Y-Y.T = \n', Y-Y.T)

Y = 
 [[ 2  3  0]
 [ 3 -4  2]
 [ 0  2 -8]]
Y.T = 
 [[ 2  3  0]
 [ 3 -4  2]
 [ 0  2 -8]]
Y-Y.T = 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


Matrices which have this
property are called *symmetric* - and this alludes to a reflection in
the *leading diagonal*, that runs from top left to bottom right. We can
also see that

$$
\boldsymbol{Y}^T=(\boldsymbol{Z}+\boldsymbol{Z}^T)^T
=\boldsymbol{Z}^T+(\boldsymbol{Z}^T)^T
=\boldsymbol{Z}^T+\boldsymbol{Z}=\boldsymbol{Y}
$$

and so adding a square matrix to its own transpose always produces a
symmetric matrix. Some writers reserve vertically symmetric letters,
such as $\boldsymbol{A},\boldsymbol{H},…$ for symmetric matrices, and
non-symmetric letters, such as $\boldsymbol{B},\boldsymbol{K},…$, for
non-symmetric matrices. We'll do this when it's practical.

> **THINK ABOUT:** Must a symmetric matrix be square? Can you add a
> non-square matrix to its own transpose? If
> $\boldsymbol{L}=\boldsymbol{K}+\boldsymbol{P}$ then what is
> $\boldsymbol{L}-\boldsymbol{P}$ equal to?

## Matrix Multiplication by a Scalar

Matrices can be multiplied by a scalar: we just have to multiply every
entry by that scalar. For example, for the matrix $\boldsymbol{B}$ given
above, we could say $\boldsymbol{C}=2\boldsymbol{B}$ so that,

$$
\boldsymbol{C}
=
2\boldsymbol{B}
=
2\left(\begin{array}{rrr}
3 & 1 & -6.2 \\
2 & -5 & \pi
\end{array}\right)
= \left(\begin{array}{rrr}
6 & 2 & -12.4 \\
4 & -10 & 2\pi
\end{array}\right).
$$

And, with `numpy` ...

In [6]:
C = 2*B
print('C = \n', C)

C = 
 [[  6.           2.         -12.4       ]
 [  4.         -10.           6.28318531]]



## Matrix Multiplication

Matrices can also be multiplied together provided that they are of compatible
shape. The process uses the same pattern as the inner (or scalar, or
dot) product of vectors. We go along the rows on the left and down the
columns on the right. For example:

$$
\text{if }
\boldsymbol{J} = \left(\begin{array}{rr}
3 & 4\\ 2 & 1
\end{array}\right)
\text{ and } 
\boldsymbol{L} = \left(\begin{array}{rrr}
1 & 5 & -7\\ -3 & -4 & 0
\end{array}\right)
\text{ then }
\boldsymbol{J}\boldsymbol{L} = \left(\begin{array}{rrr}
-9 & -1 & -21 \\ -1 & 6 & -14
\end{array}\right)
$$

To see how this happens, lay the entire calculation out in detail like
this,

$$
\left(\begin{array}{rr}
3 & 4\\ 2 & 1
\end{array}\right)
\left(\begin{array}{rrr}
1 & 5 & -7\\ -3 & -4 & 0
\end{array}\right)
 = \left(\begin{array}{rrr}
-9 & -1 & -21 \\ -1 & 6 & -14
\end{array}\right)
$$

and think about using the inner product for each row on the left of the
product, $\boldsymbol{J}$, and each column on the right of the product,
$\boldsymbol{L}$.

Your choice of row in $\boldsymbol{J}$ will give the results in that row
on the right of the $=$ sign, and your choice of column in
$\boldsymbol{L}$ will give the results in that column on the right of
the $=$ sign.

For example, to get the $-1$ in row 1 and column 2 we see that it comes
from the dot product pattern applied to the row 1 of $\boldsymbol{J}$
and column 2 of $\boldsymbol{L}$, like so

$$
\left(\begin{array}{rr}
3 & 4\\ \cdot & \cdot
\end{array}\right)
\left(\begin{array}{rrr}
\cdot & 5 & \cdot\\ \cdot & -4 & \cdot
\end{array}\right)
= \left(\begin{array}{rrr}
\cdot & (3\times 5+4\times -4) & \cdot \\ \cdot & \cdot & \cdot
\end{array}\right)
= \left(\begin{array}{ccc}
\cdot & -1 & \cdot \\ \cdot & \cdot & \cdot
\end{array}\right)
$$

Here is another way to see it,

$$
\left(\begin{array}{rr}
\rightarrow & \rightarrow\\ \cdot & \cdot
\end{array}\right)
\left(\begin{array}{rrr}
\cdot & \downarrow & \cdot\\ \cdot & \downarrow & \cdot
\end{array}\right)
= \left(\begin{array}{ccc}
\cdot & \times & \cdot \\ \cdot & \cdot & \cdot
\end{array}\right)
$$

Notice that we can only form the product $\boldsymbol{J}\boldsymbol{L}$
if the number of columns in $\boldsymbol{J}$ equals the number of rows
in $\boldsymbol{L}$. If this isn't the case then we say that
$\boldsymbol{J}\boldsymbol{L}$ **doesn't exist**.

> **THINK ABOUT:** Given a matrix $\boldsymbol{C}$, can we always form
> $\boldsymbol{C}^2 = \boldsymbol{C}\boldsymbol{C}$? What about
> $\boldsymbol{C}^3$, or $\boldsymbol{C}^4$ and so on? What about if
> $\boldsymbol{C}$ is square?

> **THINK ABOUT:** Suppose that $\boldsymbol{J}\boldsymbol{L}$ exists.
> If $\boldsymbol{J}$ has $p$ rows and $\boldsymbol{L}$ has $q$ columns,
> then what is the *dimension*, or *shape*, of
> $\boldsymbol{J}\boldsymbol{L}$?

> **THINK ABOUT:** Given matrices non-square matrices $\boldsymbol{P}$
> and $\boldsymbol{Q}$ for which $\boldsymbol{P}\boldsymbol{Q}$ exists.
> Does $\boldsymbol{Q}\boldsymbol{P}$ exist? Create two such matrices
> and form $(\boldsymbol{P}\boldsymbol{Q})^T$ and
> $\boldsymbol{Q}^T\boldsymbol{P}^T$. What do you find? Do you think
> this is always true?


## Code for matrix multiplication 

Recall that

$$
\text{if }
\boldsymbol{J} = \left(\begin{array}{rr}
3 & 4\\ 2 & 1
\end{array}\right)
\text{ and } 
\boldsymbol{L} = \left(\begin{array}{rrr}
1 & 5 & -7\\ -3 & -4 & 0
\end{array}\right)
\text{ then }
\boldsymbol{J}\boldsymbol{L} = \left(\begin{array}{rrr}
-9 & -1 & -21 \\ -1 & 6 & -14
\end{array}\right)
$$

To do this with `numpy` we use the `dot` method as follows: 

In [7]:
J = np.array([[3, 4],[2, 1]])
L = np.array([[1, 5, -7],[-3, -4, 0]])
print('JL = \n', J.dot(L))

JL = 
 [[ -9  -1 -21]
 [ -1   6 -14]]


An alternative is to use `np.dot(J,L)` like this,

In [8]:
print('JL = \n', np.dot(J,L))

JL = 
 [[ -9  -1 -21]
 [ -1   6 -14]]


**BUT:** *what we must not do is this:* `J*L`. This will give an error
Try it: use this `print('JL = \n', J*L)` for example.

To see what an expression like this does consider these matrices,

$$
\text{if }
\boldsymbol{J} = \left(\begin{array}{rr}
3 & 4\\ 2 & 1
\end{array}\right)
\text{ and } 
\boldsymbol{K} = \left(\begin{array}{rrr}
1 & 5 \\ -3 & -4
\end{array}\right)
\text{ then }
\boldsymbol{J}\boldsymbol{K} = \left(\begin{array}{rrr}
-9 & -1 \\ -1 & 6
\end{array}\right)
$$

With `numpy` this is,

In [9]:
K = np.array([[1, 5],[-3, -4]])
print('JK = \n', J.dot(K))

JK = 
 [[-9 -1]
 [-1  6]]


which should not be a surprise. Now let's see what `J*K` is... 

In [10]:
print('JK = \n', J*K)

JK = 
 [[ 3 20]
 [-6 -4]]


What just happened? Can you figure it out?

**BE CAREFUL** of this - it can cause errors (bugs) that are hard to spot.

> **THINK ABOUT:** is there a mathematical notation for this type of product?
> This is called *elementwise* multiplication - why? 
> Look up *Hadamard Product* - is it related?

## Notation

It is useful to be able to refer to the *elements* in a vector or a
matrix in a generic way. We do this with subscripts.

Given an $n$-dimensional vector $\boldsymbol{v}\in\mathbb{R}^n$, we
refer to the value in position $j$ as $v_j$.

Similarly, given an $m\times n$-dimensional matrix
$\boldsymbol{R}\in\mathbb{R}^{m,n}$, we refer to the value in row $i$,
column $j$ as $r_{ij}$ (or when confusion might arise, as $r_{i,j}$).

For example,

$$
\text{if }
\boldsymbol{b} = \left(\begin{array}{r}
6 \\ -3 \\ 2.5 \\ -1 \\ 0
\end{array}\right)
\text{ and }
\boldsymbol{N}^T = \left(\begin{array}{rrr}
-4 & 7/8 & 0 \\
 9  & 6 & 0
\end{array}\right),
$$

Then $b_4 = -1$ and $n_{1,2} = 7/8$.


## The Matrix-Vector Product

This is a partcularly important form of matrix-matrix multiplication.

A column vector is no more than a matrix with one column. This means
that we can multiply matrices and vectors providing they are of
compatible dimension. A particularly important case is the
*matrix-vector product* of the form
$\boldsymbol{B}\boldsymbol{u}=\boldsymbol{f}$. For example,

$$
\text{If }
\boldsymbol{B}
= \left(\begin{array}{rrr}
 3 & -2 & 4 \\
-6 & 6 & -11 \\
 6 & 2 & 5 \\
\end{array}\right)
\text{ and }
\boldsymbol{u}
= \left(\begin{array}{rrr}
2 \\ 0 \\ -1
\end{array}\right)
\text{ then }
\boldsymbol{f}
= \left(\begin{array}{rrr}
2 \\ -1 \\ 7
\end{array}\right)
$$

because

$$
\boldsymbol{B}\boldsymbol{u}
= \left(\begin{array}{rrr}
 3 & -2 & 4 \\
-6 & 6 & -11 \\
 6 & 2 & 5 \\
\end{array}\right)
\left(\begin{array}{rrr}
2 \\ 0 \\ -1
\end{array}\right)
=
\left(\begin{array}{rrr}
2 \\ -1 \\ 7
\end{array}\right)
$$

Let's verify this with `numpy`...

In [11]:
B = np.array( [[3, -2, 4],[-6, 6, -11],[ 6, 2, 5 ]])
u = np.array([[2], [0], [-1]])
f = B.dot(u)
print('f = \n', f) 

f = 
 [[ 2]
 [-1]
 [ 7]]


## The Matrix Inverse

A way to build on the previous calculation is to remember that for
'ordinary' (scalar) variables $b$, $u$ and $f$, if we have $bu=f$ then
if $b\ne 0$ we can multiply both sides by $b^{-1}$ and get
$b^{-1}b u = b^{-1}f$. Of course, this is just $u=f/b$, and it works
because $b^{-1}b=1$.

For matrices we can imagine doing the same thing. If
$\boldsymbol{B}\boldsymbol{u}=\boldsymbol{f}$ we might hope to be able
to write $\boldsymbol{u}=\boldsymbol{B}^{-1}\boldsymbol{f}$. If we knew
$\boldsymbol{B}$ and $\boldsymbol{f}$ this would then allow us to find
$\boldsymbol{u}=\boldsymbol{B}^{-1}\boldsymbol{f}$.

The situation is quite complicated. First note that

$$
\frac{1}{36}\left(\begin{array}{rrr}
 52 &  18 & -2 \\
-36 & -9 &   9 \\
-48 & -18 &  6
\end{array}\right)
\left(\begin{array}{rrr}
 3 & -2 & 4 \\
-6 & 6 & -11 \\
 6 & 2 & 5 \\
\end{array}\right)
=
\frac{1}{36}
\left(\begin{array}{rrr}
36 &  0 &  0 \\
 0 & 36 &  0 \\
 0 &  0 & 36\\
\end{array}\right)
=
\left(\begin{array}{rrr}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 \\
\end{array}\right).
$$

This calculation also illustrates the general rule given above that if
we multiply a matrix by a scalar then we should multiply every value in
that matrix by that scalar.

The matrix on the right is called the identity matrix. Here it is
three-by-three but such a square matrix exists for every dimension. It
is always zero everywhere except on the leading diagonal where the
entries are always unity.

The identity matrix is, for us, always denoted by $\boldsymbol{I}$ and
plays the role of $1$ in matrix theory. So, by analogy with $b^{-1}b=1$
above, the above calculation suggests
$\boldsymbol{B}^{-1}\boldsymbol{B}=\boldsymbol{I}$ where

$$
\boldsymbol{B}^{-1} =
\frac{1}{36}\left(\begin{array}{rrr}
 52 &  18 & -2 \\
-36 & -9 &   9 \\
-48 & -18 &  6
\end{array}\right).
$$

In this expression $36$ is the value of the *determinant* of
$\boldsymbol{B}$. If this value were zero then this *inverse matrix*
would not be defined.

## Determinant of a Square Matrix

The determinant is a difficult quantity to define and work with. It can
only be defined for square matrices where, for a square matrix
$\boldsymbol{K}$, its determinant is denoted by $\det(\boldsymbol{K})$.

Consider first the case of a $2 \times 2$ matrix:

$$
\text{if }\boldsymbol{K} = \left(\begin{array}{rr}
a & b \\ c & d
\end{array}\right)
\text{ then } 
\det(\boldsymbol{K}) = ad-bc
\text{ and }
\boldsymbol{K}^{-1} = \frac{1}{\det(\boldsymbol{K})}
\left(\begin{array}{rr}
d & -b \\ -c & a
\end{array}\right)
$$

if, and only if, $\det(\boldsymbol{K})\ne 0$. You can check that for
yourself. The more general case is far more difficult to discuss so here
we will merely accept this general result:

> **INVERSE MATRIX:** a square matrix $\boldsymbol{K}$ is invertible if
> and only if its determinant is non-zero. Its inverse satisfies
> $\boldsymbol{K}^{-1}\boldsymbol{K}=\boldsymbol{I}$.

In practice it is usually very very difficult to check whether or not
$\det(\boldsymbol{K})\ne 0$. However, fortunately, the application area
we are working on will often give us either a good clue, or a definite
answer. We'll see a few examples of this as we go along. With the first
application forming the next subsection.

> **THINK ABOUT:** Create a matrix $\boldsymbol{P}$ for which
> $\boldsymbol{P}^{-1}$ exists (or use the one above) and investigate
> how $\boldsymbol{P}\boldsymbol{P}^{-1}$ and
> $\boldsymbol{P}^{-1}\boldsymbol{P}$ are related. Do you think this is
> always true?

> **THINK ABOUT:** Create another matrix $\boldsymbol{Q}$ for which both
> $\boldsymbol{Q}\boldsymbol{P}$ and
> $(\boldsymbol{Q}\boldsymbol{P})^{-1}$ exist. How does this last
> quantity relate to $\boldsymbol{P}^{-1}\boldsymbol{Q}^{-1}$? Do you
> think this is always true?

## Never do this - unless you know you need to

In practice we rarely if ever need to actually obtain the inverse
or the determinant of a matrix. 

We can obtain these using `numpy` as follows... 

In [12]:
print('det(B) = ', np.linalg.det(B)) 
# multiply the inverse by 36 to tidy up the output...
print('inverse of B = \n', 36*np.linalg.inv(B)) 

det(B) =  36.0
inverse of B = 
 [[ 52.  18.  -2.]
 [-36.  -9.   9.]
 [-48. -18.   6.]]


We can verify the inverse by checking that
$\boldsymbol{B}\boldsymbol{B}^{-1} = \boldsymbol{I}$ as follows,

In [13]:
print('B*B^(-1) = \n', B.dot(np.linalg.inv(B))) 

B*B^(-1) = 
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  2.77555756e-17]
 [-2.22044605e-16  0.00000000e+00  1.00000000e+00]]


Notice the *small* numbers - this isn't unusual in computing.
The numerical precision in the processor is limited, and so
the arithmetic is not exact. This is sometimes a problem, but usually
not. If we enounter it as a problem, we'll discuss it.

We ought to check that
$\boldsymbol{B}^{-1}\boldsymbol{B} = \boldsymbol{I}$ also...

In [14]:
print('B^(-1)*B = \n', np.linalg.inv(B).dot(B)) 

B^(-1)*B = 
 [[ 1.00000000e+00  6.93889390e-17 -4.85722573e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17 -1.66533454e-16  1.00000000e+00]]



## Review

IN the above:

- we reviewed the mathematical notion of a *matrix*.
- we saw how using `numpy` in `python` we could
  - create matrices;
  - add and subtract them, and multiply by a scalar;
  - form matrix-vector products;
  - form element-wise products

We will be building extensively on these skills in the coming weeks.

Note again that we very rarely explicitly need the inverse of a matrix 
or a matrix determinant. These can be easy to determine for small matrices,
as we saw above, but as the matrices become larger they take a very long time
to compute. Avoid them at all costs.


## Exercises

1. What does `L.shape` give? (Look at the dimensions of $\boldsymbol{L}$.)

1. What does `L.ndim` give? ($\boldsymbol{L}$ is two-dimensional.)

1. Examine these statements. What do they do?
 - `np.ones(3)`
 - `np.ones([3,1])`
 - `np.ones([2,4])`
 - `np.zeros([2,4])`
 - `np.eye(4)`

2. What about these?
 - `np.arange(4)`
 - `np.arange(2,8)`
 - `np.arange(2,9,2)`
 - `np.linspace(4,9,num=6)`
 - `np.linspace(4,9,num=11)`
 
3. Try these - explain the results: 
 - `D = L.reshape([3,2])`
 - `E = L.reshape([6,])`

3. `numpy` is very powerful: see this introduction for more details  <https://numpy.org/doc/stable/user/absolute_beginners.html>


In [15]:
L.ndim

2

In [16]:
L.shape

(2, 3)

In [17]:
print(np.ones(3))
print(np.ones([3,1]))
print(np.ones([2,4]))
print(np.zeros([2,4]))
print(np.eye(4))

[1. 1. 1.]
[[1.]
 [1.]
 [1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
print(np.arange(4))
print(np.arange(2,8))
print(np.arange(2,9,2))
print(np.linspace(4,9,num=6))
print(np.linspace(4,9,num=11))




[0 1 2 3]
[2 3 4 5 6 7]
[2 4 6 8]
[4. 5. 6. 7. 8. 9.]
[4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9. ]


In [19]:
print('L = \n', L)
D = L.reshape([3,2])
print('D = \n', D)
E = L.reshape([6,])
print('E = \n', E)

L = 
 [[ 1  5 -7]
 [-3 -4  0]]
D = 
 [[ 1  5]
 [-7 -3]
 [-4  0]]
E = 
 [ 1  5 -7 -3 -4  0]


### Technical Notes

This originated from
<https://stackoverflow.com/questions/38540326/save-html-of-a-jupyter-notebook-from-within-the-notebook>

These lines create a back up of the notebook. They can be ignored.

At some point this is better as a bash script outside of the notebook


In [20]:
%%bash
NBROOTNAME='5_matrices'
OUTPUTTING=1

if [ $OUTPUTTING -eq 1 ]; then
  jupyter nbconvert --to html $NBROOTNAME.ipynb
  cp $NBROOTNAME.html ../backups/$(date +"%m_%d_%Y-%H%M%S")_$NBROOTNAME.html
  mv -f $NBROOTNAME.html ./formats/html/

  jupyter nbconvert --to pdf $NBROOTNAME.ipynb
  cp $NBROOTNAME.pdf ../backups/$(date +"%m_%d_%Y-%H%M%S")_$NBROOTNAME.pdf
  mv -f $NBROOTNAME.pdf ./formats/pdf/

  jupyter nbconvert --to script $NBROOTNAME.ipynb
  cp $NBROOTNAME.py ../backups/$(date +"%m_%d_%Y-%H%M%S")_$NBROOTNAME.py
  mv -f $NBROOTNAME.py ./formats/py/
else
  echo 'Not Generating html, pdf and py output versions'
fi

[NbConvertApp] Converting notebook 5_matrices.ipynb to html
[NbConvertApp] Writing 631776 bytes to 5_matrices.html
[NbConvertApp] Converting notebook 5_matrices.ipynb to pdf
[NbConvertApp] Writing 61267 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', 'notebook.tex', '-quiet']
[NbConvertApp] Running bibtex 1 time: ['bibtex', 'notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 99182 bytes to 5_matrices.pdf
[NbConvertApp] Converting notebook 5_matrices.ipynb to script
[NbConvertApp] Writing 23293 bytes to 5_matrices.py
