# Linear Algebra: Review of Vectors and Matrices

#### *variationalform* <https://variationalform.github.io/>

#### *Just Enough: progress at pace*

<https://variationalform.github.io/>

<https://github.com/variationalform>

<https://www.brunel.ac.uk/people/simon-shaw>.


<table>
<tr>
<td>
<img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" style="height:18px"/>
<img src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" style="height:18px"/>
<img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" style="height:18px"/>
</td>
<td>

<p>
This work is licensed under CC BY-SA 4.0 (Attribution-ShareAlike 4.0 International)

<p>
Visit <a href="http://creativecommons.org/licenses/by-sa/4.0/">http://creativecommons.org/licenses/by-sa/4.0/</a> to see the terms.
</td>
</tr>
</table>

<table>
<tr>
<td>This document uses</td>
<td>
<img src="https://www.python.org/static/community_logos/python-logo-master-v3-TM.png" style="height:30px"/>
</td>
<td>and also makes use of LaTeX </td>
<td>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/LaTeX_logo.svg/320px-LaTeX_logo.svg.png" style="height:30px"/>
</td>
<td>in Markdown</td> 
<td>
<img src="https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png" style="height:30px"/>
</td>
</tr>
</table>

Standard imports

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
# beware...
M = np.array([[1,2],[3,4]])
print(M)
print(M)
print(M*M)
print(M.dot(M))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


Example distance. Find the shortest distance from the point $Q$ at coordinates
$(2,1)$ to the line with $\boldsymbol{w}=(-1,1)^T$ and $\phi=1$.

Solution: 

$$
d = \frac{\phi-\boldsymbol{w}^T\boldsymbol{q}}{\Vert\boldsymbol{w}\Vert_2}
$$

with $\boldsymbol{q}=(2,1)^T$.

In [3]:
w = np.array([[-1],[1]])
q = np.array([[2],[1]])
phi = 1
print(w)
print(q)
print(np.linalg.norm(w))
d = (phi - np.ndarray.item(w.T.dot(q)))/np.linalg.norm(w)
print(d)
d = (phi - np.matmul(w.T,q))/np.linalg.norm(w)
print(d)
d = (phi - np.vdot(w.T,q))/np.linalg.norm(w)
print(d)

[[-1]
 [ 1]]
[[2]
 [1]]
1.4142135623730951
1.414213562373095
[[1.41421356]]
1.414213562373095


In [4]:
# eigenvalues of symmetric matrix
A = np.array([[3,-2,4],[-2,6,2],[4,2,5]])
w, V = np.linalg.eig(A)
D=np.diag(w)
print('A=\n',A,'\n','w=\n',w,'\n','D=\n',D,'\n','V=\n',V)
print('V V^T = ...\n',V.dot(V.T))
print('\n error ...\n',A-V.dot(D.dot(V.T)))
# slicing: V[:,0]*V[:,0].T wont work. See ...
# https://stackoverflow.com/questions/29635501/row-vs-column-vector-return-during-numpy-array-slicing
print('\n recon ...')
print(D[0,0]*V[:,0:1]*V[:,0:1].T+D[1,1]*V[:,1:2]*V[:,1:2].T+D[2,2]*V[:,2:3]*V[:,2:3].T)

print('sum =', np.sum(A-V.dot(D.dot(V.T))) )
assert np.sum(A-V.dot(D.dot(V.T))) < 0.0001


A=
 [[ 3 -2  4]
 [-2  6  2]
 [ 4  2  5]] 
 w=
 [-1.21699057  8.21699057  7.        ] 
 D=
 [[-1.21699057  0.          0.        ]
 [ 0.          8.21699057  0.        ]
 [ 0.          0.          7.        ]] 
 V=
 [[ 7.26085219e-01  5.22302838e-01 -4.47213595e-01]
 [ 3.63042610e-01  2.61151419e-01  8.94427191e-01]
 [-5.83952325e-01  8.11787954e-01  2.85088132e-16]]
V V^T = ...
 [[ 1.00000000e+00 -1.55686504e-16  3.16593922e-16]
 [-1.55686504e-16  1.00000000e+00 -3.00120936e-16]
 [ 3.16593922e-16 -3.00120936e-16  1.00000000e+00]]

 error ...
 [[-5.32907052e-15  2.66453526e-15 -3.55271368e-15]
 [ 2.22044605e-15  2.66453526e-15  4.44089210e-16]
 [-4.44089210e-15  6.66133815e-16  8.88178420e-16]]

 recon ...
[[ 3. -2.  4.]
 [-2.  6.  2.]
 [ 4.  2.  5.]]
sum = -3.774758283725532e-15


In [5]:
E = np.zeros(A.shape)
for i in range(0,3):
    E = E + D[i,i]*np.matmul(V[:,i:i+1],V[:,i:i+1].T)
    print('E=\n',E)
    print('(A-E)/A', (A-E)/A)



E=
 [[-0.64159712 -0.32079856  0.51600297]
 [-0.32079856 -0.16039928  0.25800148]
 [ 0.51600297  0.25800148 -0.41499417]]
(A-E)/A [[1.21386571 0.83960072 0.87099926]
 [0.83960072 1.02673321 0.87099926]
 [0.87099926 0.87099926 1.08299883]]
E=
 [[1.6 0.8 4. ]
 [0.8 0.4 2. ]
 [4.  2.  5. ]]
(A-E)/A [[ 4.66666667e-01  1.40000000e+00 -1.33226763e-15]
 [ 1.40000000e+00  9.33333333e-01  1.11022302e-15]
 [-1.33226763e-15  1.11022302e-15  1.77635684e-16]]
E=
 [[ 3. -2.  4.]
 [-2.  6.  2.]
 [ 4.  2.  5.]]
(A-E)/A [[-1.62832710e-15 -1.33226763e-15 -1.11022302e-15]
 [-1.33226763e-15  4.44089210e-16  2.22044605e-16]
 [-1.11022302e-15  2.22044605e-16  1.77635684e-16]]


In [6]:
%%bash
NBROOTNAME='5a_linalg'
OUTPUTTING=1

if [ $OUTPUTTING -eq 1 ]; then
  jupyter nbconvert --to html $NBROOTNAME.ipynb
  cp $NBROOTNAME.html ../backups/$(date +"%m_%d_%Y-%H%M%S")_$NBROOTNAME.html
  mv -f $NBROOTNAME.html ./formats/html/

  jupyter nbconvert --to pdf $NBROOTNAME.ipynb
  cp $NBROOTNAME.pdf ../backups/$(date +"%m_%d_%Y-%H%M%S")_$NBROOTNAME.pdf
  mv -f $NBROOTNAME.pdf ./formats/pdf/

  jupyter nbconvert --to script $NBROOTNAME.ipynb
  cp $NBROOTNAME.py ../backups/$(date +"%m_%d_%Y-%H%M%S")_$NBROOTNAME.py
  mv -f $NBROOTNAME.py ./formats/py/
else
  echo 'Not Generating html, pdf and py output versions'
fi

[NbConvertApp] Converting notebook 5a_linalg.ipynb to html
[NbConvertApp] Writing 591195 bytes to 5a_linalg.html
[NbConvertApp] Converting notebook 5a_linalg.ipynb to pdf
[NbConvertApp] Writing 33908 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', 'notebook.tex', '-quiet']
[NbConvertApp] Running bibtex 1 time: ['bibtex', 'notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 50975 bytes to 5a_linalg.pdf
[NbConvertApp] Converting notebook 5a_linalg.ipynb to script
[NbConvertApp] Writing 3752 bytes to 5a_linalg.py
