# Matrix Decompositions

#### *variationalform* <https://variationalform.github.io/>

#### *Just Enough: progress at pace*

<https://variationalform.github.io/>

<https://github.com/variationalform>

Simon Shaw
<https://www.brunel.ac.uk/people/simon-shaw>.


<table>
<tr>
<td>
<img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" style="height:18px"/>
<img src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" style="height:18px"/>
<img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" style="height:18px"/>
</td>
<td>

<p>
This work is licensed under CC BY-SA 4.0 (Attribution-ShareAlike 4.0 International)

<p>
Visit <a href="http://creativecommons.org/licenses/by-sa/4.0/">http://creativecommons.org/licenses/by-sa/4.0/</a> to see the terms.
</td>
</tr>
</table>

<table>
<tr>
<td>This document uses</td>
<td>
<img src="https://www.python.org/static/community_logos/python-logo-master-v3-TM.png" style="height:30px"/>
</td>
<td>and also makes use of LaTeX </td>
<td>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/LaTeX_logo.svg/320px-LaTeX_logo.svg.png" style="height:30px"/>
</td>
<td>in Markdown</td> 
<td>
<img src="https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png" style="height:30px"/>
</td>
</tr>
</table>

## What this is about:

You will be introduced to ...

- Methods for decomposing matrices in to alternative forms.
- Eigenvalues and Eigenvectors of square matrices.
- The singular Value Decomposition for general matrices
- Using `numpy` to compute these decompositions.

As usual our emphasis will be on *doing* rather than *proving*:
*just enough: progress at pace*


## Assigned Reading

For this worksheet you should read CVhapter 7 of [FCLA], and
Chapters 4 of [MML].

- MML: Mathematics for Machine Learning, by Marc Peter Deisenroth, A. Aldo Faisal, and Cheng Soon Ong.
  Cambridge University Press. <https://mml-book.github.io>.
- FCLA: A First Course in Linear Algebra, by Ken Kuttler, 
  <https://math.libretexts.org/Bookshelves/Linear_Algebra/A_First_Course_in_Linear_Algebra_(Kuttler)>
 
All of the above can be accessed legally and without cost.

There are also these useful references for coding:

- PT: `python`: <https://docs.python.org/3/tutorial>
- NP: `numpy`: <https://numpy.org/doc/stable/user/quickstart.html>
- MPL: `matplotlib`: <https://matplotlib.org>



## Eigenvalues and Eigenvectors

Consider this matrix and vector,

$$
\boldsymbol{B}
= \left(\begin{array}{rrr}
 3 & -2 & 4 \\
-6 & 6 & -11 \\
 6 & 2 & 5 \\
\end{array}\right)
\qquad\text{ and }\qquad
\boldsymbol{x}
= \left(\begin{array}{r}
-2 \\
 3 \\
 1 \\
\end{array}\right)
\qquad\text{ then }\qquad
\boldsymbol{B}\boldsymbol{x}
= \left(\begin{array}{r}
-8 \\
 19 \\
-1 \\
\end{array}\right)
$$

and notice that $\boldsymbol{B}$ *mixes up* $\boldsymbol{x}$ to such an
extent that $\boldsymbol{B}\boldsymbol{x}$ bears no relationship to the
original $\boldsymbol{x}$. This isn't so surprising when you think about
it.

We can do this in `python` using `numpy` as follows...

In [1]:
import numpy as np
B = np.array( [[3, -2, 4],[-6, 6, -11],[ 6, 2, 5 ]])
x = np.array([[-2], [3], [1]])
f = B.dot(x)
print('f = \n', f) 

f = 
 [[-8]
 [19]
 [-1]]


On the other hand, consider this matrix with a different vector,

$$
\boldsymbol{B}
= \left(\begin{array}{rrr}
 3 & -2 & 4 \\
-6 & 6 & -11 \\
 6 & 2 & 5 \\
\end{array}\right)
\qquad\text{ and }\qquad
\boldsymbol{w}
= \left(\begin{array}{r}
-2 \\
 5 \\
 2 \\
\end{array}\right).
$$ This time,

$$
\boldsymbol{B}\boldsymbol{w}
= \left(\begin{array}{rrr}
 3 & -2 & 4 \\
-6 & 6 & -11 \\
 6 & 2 & 5 \\
\end{array}\right)
\left(\begin{array}{r}
-2 \\
 5 \\
 2 \\
\end{array}\right)
=
\left(\begin{array}{r}
-8 \\
 20 \\
 8 \\
\end{array}\right)
=
4\left(\begin{array}{r}
-2 \\
 5 \\
 2 \\
\end{array}\right)
=
4\boldsymbol{w}
$$ So $\boldsymbol{B}\boldsymbol{w}=4\boldsymbol{w}$, and all
$\boldsymbol{B}$ does is magnify $\boldsymbol{w}$ to be $4$ times
longer.

### Exercise:
use `python` to show that $\frac{1}{4}\boldsymbol{B}\boldsymbol{w}-\boldsymbol{w}=\boldsymbol{0}$

In [2]:
B = np.array( [[3, -2, 4],[-6, 6, -11],[ 6, 2, 5 ]])
w = np.array([[-2], [5], [2]])
f = 0.25*B.dot(w)
print('f - w = \n', f-w) 
# or many other variants, such as
print('result = \n', 0.25*B.dot(w)-w) 

f - w = 
 [[0.]
 [0.]
 [0.]]
result = 
 [[0.]
 [0.]
 [0.]]


This seems more surprising. Here $4$ is called an *eigenvalue* ('own
value') of $\boldsymbol{B}$ and $\boldsymbol{w}$ is the corresponding
*eigenvector*.

In general, for any square matrix $\boldsymbol{B}$ the problem of
finding scalars $\lambda$ and vectors $\boldsymbol{v}$ such that

$$
\boldsymbol{B}\boldsymbol{v}=\lambda\boldsymbol{v}
$$ is called an *eigenvalue problem*. The following facts are known to
be true:

> **The Eigenvalue Theorem.** Every square matrix of dimension $n$ has
> $n$ eigenvalue-eigenvector pairs,
> $(\lambda_1,\boldsymbol{v}_1), (\lambda_2,\boldsymbol{v}_2),\ldots, (\lambda_n,\boldsymbol{v}_n)$.
> The eigenvalues need not be distinct, and the eigenvector lengths are
> arbitrary. **A matrix which has one or more zero eigenvalues is not
> invertible.** On the other hand, **If the eigenvalues of a matrix are
> all non-zero then that matrix is invertible**, and it has **full
> rank**. The determinant of a matrix is the product of its eigenvalues.

### Example 1

For $\boldsymbol{B}$ above we have that

$$
\boldsymbol{B}\boldsymbol{v}=\lambda\boldsymbol{v}
$$

for
$(\lambda_1,\boldsymbol{v}_1), (\lambda_2,\boldsymbol{v}_2), (\lambda_3,\boldsymbol{v}_3)$
given by

$$
9 \text{ with }
\left(\begin{array}{r}
 17 \\
-45 \\   
 3 \\
\end{array}\right),
\qquad\text{ with }\qquad
1 \text{ with }
\left(\begin{array}{r}
-1 \\
 1 \\
 1
\end{array}\right)
\qquad\text{ and }\qquad
4 \text{ with }
\left(\begin{array}{r}
  -2 \\
   5 \\
   2
\end{array}\right).
$$

We have already seen the case $\lambda = 4$ and
$\boldsymbol{v}=(-2,5,2)^T$ above.

The eigenvectors are not unique - they can be multiplied by an arbitrary
(non-zero) scalar and they remain eigenvectors. For that reason it is
usual to *normalize* an eigenvector by dividing through by its length,
as given by the (Euclidean, Pythagorean) $2$-norm, $\Vert\cdot\Vert_2$.
For example, for $\boldsymbol{v}=(-2,5,2)^T$ we have

$$
\Vert\boldsymbol{v}\Vert_2 = \sqrt{(-2)^2+5^2+2^2} = \surd{33} 
$$

which means that

$$
\boldsymbol{v} = \frac{1}{\sqrt{33}}\left(\begin{array}{r}
-2 \\ 5 \\ 2
\end{array}\right)
=
\left(\begin{array}{r}
  -0.348155311911396 \\
   0.870388279778489 \\
      0.348155311911395
\end{array}\right)
$$ is also an eigenvector for the eigenvalue $\lambda = 4$.

> **THINK ABOUT:** An eigenpair satisfies
> $\boldsymbol{B}\boldsymbol{v}=\lambda\boldsymbol{v}$. Choose a
> non-zero real number $\alpha$ and write
> $\boldsymbol{w}=\alpha\boldsymbol{v}$. Is it true that
> $\boldsymbol{B}\boldsymbol{w}=\lambda\boldsymbol{w}$? Can you see why
> eigenvectors are not unique in length?

> **THINK ABOUT:** If we choose $\alpha = \Vert\boldsymbol{v}\Vert_2^{-1}$
> above what can you say about the value of $\Vert\boldsymbol{w}\Vert_2$?

If we normalize each of the eigenvectors above with their own length we
get something like this (the decimals may go on for ever - why?):

$$
9 \text{ with }
\left(\begin{array}{r}
 0.3527\ldots \\
-0.9336\ldots \\   
 0.0622\ldots \\
\end{array}\right),
\qquad\text{ with }\qquad
1 \text{ with }
\left(\begin{array}{r}
-0.5773\ldots \\
 0.5773\ldots \\
 0.5773\ldots
\end{array}\right)
\qquad\text{ and }\qquad
4 \text{ with }
\left(\begin{array}{r}
  -0.3481\ldots \\
   0.8703\ldots \\
   0.3481\ldots
\end{array}\right).
$$

Let's use `numpy` to calculate the eigensystem for $\boldsymbol{B}$.
It goes like this...

In [3]:
w, V = np.linalg.eig(B)
print(w)
print(V)

[9. 1. 4.]
[[ 0.35271531 -0.57735027 -0.34815531]
 [-0.93365819  0.57735027  0.87038828]
 [ 0.06224388  0.57735027  0.34815531]]


Yu can see that two quantities are returned, `w` and `V`. The eigenvalues are
collected in `w` and the corresponding eigenvectors are the columns of `W`.

Note that the third column of `W` agrees with our calculation above as the
normalized eigenvector for the eigenvalue $\lambda = 4$.

## The Eigen-System

As indicated by this computation,
we can stack the length-normalized eigenvectors together next to each
other, with the eigenvalues in on the leading diagonal of an otherwise
empty matrix. We also make sure that the eigenvectors appear in the same
order as the corresponding eigenvalues and then use the fact that
$\boldsymbol{B}\boldsymbol{v}=\lambda \boldsymbol{v}$ for each
eigen-pair. Then entire eigen-system can then be represented in one
equation. For example,

$$
\begin{split}
\left(\begin{array}{rrr}
 3 & -2 & 4 \\
-6 & 6 & -11 \\
 6 & 2 & 5 \\
\end{array}\right)
\left(\begin{array}{rrr}
 0.3527\ldots & -0.5773\ldots &  -0.3481\ldots \\
-0.9336\ldots &  0.5773\ldots &   0.8703\ldots \\
 0.0622\ldots &  0.5773\ldots &   0.3481\ldots \\
\end{array}\right)
\\\ \\
\qquad {}=
\left(\begin{array}{rrr}
 0.3527\ldots & -0.5773\ldots &  -0.3481\ldots \\
-0.9336\ldots &  0.5773\ldots &   0.8703\ldots \\
 0.0622\ldots &  0.5773\ldots &   0.3481\ldots \\
\end{array}\right)
\left(\begin{array}{rrr}
 9 & 0 & 0 \\
 0 & 1 & 0 \\
 0 & 0 & 4 \\
\end{array}\right)
\end{split}
$$

We can write this as

$$
\boldsymbol{B}\boldsymbol{V} = \boldsymbol{V}\boldsymbol{D}
$$

where the columns of $\boldsymbol{V}$ are the eigenvectors of
$\boldsymbol{B}$, and the diagonal matrix $\boldsymbol{D}$ has the
eigenvalues on the leading diagonal. The left-to-right order of the
eigenvalues in $\boldsymbol{D}$ matches the order that the eigenvectors
appear in $\boldsymbol{V}$.

All three of these matrices are square and they each have the same
dimension as $\boldsymbol{B}$.

Now, suppose that $\det(\boldsymbol{V})\ne 0$, then
$\boldsymbol{V}^{-1}$ exists and we can (pre-)multiply both sides of
$\boldsymbol{B}\boldsymbol{V} = \boldsymbol{V}\boldsymbol{D}$ by
$\boldsymbol{V}^{-1}$ and get,

$$
\boldsymbol{V}^{-1}\boldsymbol{B}\boldsymbol{V} =
\boldsymbol{V}^{-1}\boldsymbol{V}\boldsymbol{D} = \boldsymbol{D}.
$$

We see that this has produced a diagonal matrix
$\boldsymbol{V}^{-1}\boldsymbol{B}\boldsymbol{V}$ that is similar to
$\boldsymbol{B}$ in the sense that it has the same eigenvalues. Such an
operation is called a *similarity transformation*.

On the other hand, we can (post-)multiply both sides of
$\boldsymbol{B}\boldsymbol{V} = \boldsymbol{V}\boldsymbol{D}$ by
$\boldsymbol{V}^{-1}$ and get,

$$
\boldsymbol{B} =
\boldsymbol{B}\boldsymbol{V}\boldsymbol{V}^{-1} =
\boldsymbol{V}\boldsymbol{D}\boldsymbol{V}^{-1}.
$$

One reason why this is useful is that we can now easily raise
$\boldsymbol{B}$ to powers. For example,

$$
\boldsymbol{B}^2 =
(\boldsymbol{V}\boldsymbol{D}\boldsymbol{V}^{-1})
(\boldsymbol{V}\boldsymbol{D}\boldsymbol{V}^{-1})
=\boldsymbol{V}\boldsymbol{D}^2\boldsymbol{V}^{-1}.
$$ and so on.

However, to do this we needed to assume that
$\det(\boldsymbol{V})\ne 0$, and this need not be the case. Matrices for
which this is true are called *diagonalizable*, and matrices for which
it isn't true are called *defective*.

## Eigen-systems of Symmetric Matrices

The eigenvalues and eigenvectors of a general square matrix could be
**complex numbers** (which we aren't going to be too concerned with),
and for large matrices the inverse $\boldsymbol{V}^{-1}$ could be hard
to find explicitly.

However, in the special case of a symmetric matrix $\boldsymbol{A}$, the
eigensystem $\boldsymbol{A}\boldsymbol{v}=\lambda\boldsymbol{A}$ is made
up exclusively of *real numbers*.

Furthermore, the matrix of normalized eigenvectors, $\boldsymbol{V}$, is
an orthogonal matrix. This means that
$\boldsymbol{V}^{-1}=\boldsymbol{V}^T$ - which is very easy to
calculate once $\boldsymbol{V}$ is known.

Let's see an example of this.

$$
\text{if }
\boldsymbol{A} = \left(\begin{array}{rrr}
 3 & -2 & 4  \\
-2 &  6 & 2  \\
 4 &  2 & 5
\end{array}\right)
$$

then (with some rounding),

$$
\boldsymbol{D} \approx \left(
\begin{array}{rrr}
-1.217 &  0     & 0 \\
 0     &  8.217 & 0 \\
 0     &  0     & 7  
\end{array}
\right) \quad\text{ and }\quad \boldsymbol{V} \approx \left(
\begin{array}{rrr}
 .726 & .522 & -.447 \\
 .363 & .261 &  .894 \\
-.584 & .812 &  0 \\
\end{array}
\right)
$$

### Exercise

- verify this with code.
- verify that $\boldsymbol{V}^{-1}=\boldsymbol{V}^T$. Hint: `D=np.diag(w)`.
- verify also that $\boldsymbol{A}=\boldsymbol{V}\boldsymbol{D}\boldsymbol{V}^T$



In [4]:
# possible solution
A = np.array([[3,-2,4],[-2,6,2],[4,2,5]])
w, V = np.linalg.eig(A)
D=np.diag(w)
print('A=\n',A,'\n','w=\n',w,'\n','D=\n',D,'\n','V=\n',V)
print('V V^T = ...\n',V.dot(V.T))
print('\n error ...\n',A-V.dot(D.dot(V.T)))

print('sum =', np.sum(A-V.dot(D.dot(V.T))) )
assert np.sum(A-V.dot(D.dot(V.T))) < 0.0001

A=
 [[ 3 -2  4]
 [-2  6  2]
 [ 4  2  5]] 
 w=
 [-1.21699057  8.21699057  7.        ] 
 D=
 [[-1.21699057  0.          0.        ]
 [ 0.          8.21699057  0.        ]
 [ 0.          0.          7.        ]] 
 V=
 [[ 7.26085219e-01  5.22302838e-01 -4.47213595e-01]
 [ 3.63042610e-01  2.61151419e-01  8.94427191e-01]
 [-5.83952325e-01  8.11787954e-01  2.85088132e-16]]
V V^T = ...
 [[ 1.00000000e+00 -1.55686504e-16  3.16593922e-16]
 [-1.55686504e-16  1.00000000e+00 -3.00120936e-16]
 [ 3.16593922e-16 -3.00120936e-16  1.00000000e+00]]

 error ...
 [[-5.32907052e-15  2.66453526e-15 -3.55271368e-15]
 [ 2.22044605e-15  2.66453526e-15  4.44089210e-16]
 [-4.44089210e-15  6.66133815e-16  8.88178420e-16]]
sum = -3.774758283725532e-15


The calculation verifies that $\boldsymbol{V}^T\boldsymbol{V}=\boldsymbol{I}$
up to rounding error.

Our check also confirms that $\boldsymbol{A}\boldsymbol{V}=\boldsymbol{V}\boldsymbol{D}$.


## The Eigen-Decomposition

Furthermore, we can also write
$\boldsymbol{A}\boldsymbol{V}=\boldsymbol{V}\boldsymbol{D}$ in expanded
form,

$$
\boldsymbol{A} =
(\boldsymbol{v}_1\ \boldsymbol{v}_2\ \boldsymbol{v}_3\ \ldots)
\left(\begin{array}{rrrr}
\lambda_1     \\
& \lambda_2   \\
& & \lambda_3 \\
& & & \ \ \ddots
\end{array}\right)
\left(\begin{array}{rrrr}
\boldsymbol{v}_1^T\\ \boldsymbol{v}_2^T\\ \boldsymbol{v}_3^T\\ \vdots
\end{array}\right)
$$

(we haven't shown all the zero elements) and then simplify this to get

$$
\boldsymbol{A} =
(\boldsymbol{v}_1\ \boldsymbol{v}_2\ \boldsymbol{v}_3\ \ldots)
\left(\begin{array}{cccc}
\lambda_1\boldsymbol{v}_1^T \\
\lambda_2\boldsymbol{v}_2^T \\
\lambda_3\boldsymbol{v}_3^T \\ \vdots
\end{array}\right)
=
\lambda_1\boldsymbol{v}_1\boldsymbol{v}_1^T
+
\lambda_2\boldsymbol{v}_2\boldsymbol{v}_2^T
+
\lambda_3\boldsymbol{v}_3\boldsymbol{v}_3^T
+ \cdots
= 
\sum_{k=1}^n
\lambda_k\boldsymbol{v}_k\boldsymbol{v}_k^T
$$

Let's see this in python. We start by getting the eigen-system.

In [5]:
A = np.array([[3,-2,4],[-2,6,2],[4,2,5]])
w, V = np.linalg.eig(A)
D=np.diag(w)

Let's look at each decomposed term in turn. First, for the $k=1$ term,

In [6]:
print( D[0,0]*V[:,0:1]*V[:,0:1].T )

[[-0.64159712 -0.32079856  0.51600297]
 [-0.32079856 -0.16039928  0.25800148]
 [ 0.51600297  0.25800148 -0.41499417]]


Let's think about what is going on here. We are printing out the quantity

```python
D[0,0]*V[:,0:1]*V[:,0:1].T
```

In this, the `D[0,0]` factor is just the eigenvalue from the top left
(first row, first column) of the $\boldsymbol{D}$ matrix. 

Then, next, `V[:,0:1]` is a `numpy` **slice**.

In this type of expression `[c,a:b]` means take the elements in row `c` 
that occupy columns `a` through to `b-1`. The expression `[:,a:b]` means
take all the rows. Remember that column and row numbering starts at zero
in `numpy`.

So, `V[:,0:1]` says take the first column of `V` - a column vector, 
and `V[:,0:1].T` says take the transpose of the first solumn of `V`.

It is important to note that we have to write our slicing
expressions in the form  `V[:,0:1]` rather than `V[:,0]`,
otherwise we lose the shape. See e.g.
<https://stackoverflow.com/questions/29635501/row-vs-column-vector-return-during-numpy-array-slicing>

Here is a demo:

In [7]:
print('V = \n', V)
print('V[:,0:1] = \n', V[:,0:1])
print('V[:,0] = \n', V[:,0])

V = 
 [[ 7.26085219e-01  5.22302838e-01 -4.47213595e-01]
 [ 3.63042610e-01  2.61151419e-01  8.94427191e-01]
 [-5.83952325e-01  8.11787954e-01  2.85088132e-16]]
V[:,0:1] = 
 [[ 0.72608522]
 [ 0.36304261]
 [-0.58395233]]
V[:,0] = 
 [ 0.72608522  0.36304261 -0.58395233]


Therefore, for $k=1$ we can write $\lambda_k\boldsymbol{v}_k\boldsymbol{v}_k^T$
in code as `D[0,0]*V[:,0:1]*V[:,0:1].T`.

The full reconstruction of $\boldsymbol{A}$ is then...

In [8]:
print('\n The reconstruction of A ...')
print(D[0,0]*V[:,0:1]*V[:,0:1].T + D[1,1]*V[:,1:2]*V[:,1:2].T + D[2,2]*V[:,2:3]*V[:,2:3].T)


 The reconstruction of A ...
[[ 3. -2.  4.]
 [-2.  6.  2.]
 [ 4.  2.  5.]]


### Exercise

Find the eigen-decomposition of the matrix

$$
\boldsymbol{T} = \left(\begin{array}{rrr}
 7 & -3 & -9 \\
-3 & -5 &  2 \\
-9 &  2 & 10
\end{array}\right)
$$

Order the eigenvalues so that 
$\vert\lambda_1\vert \ge \vert\lambda_2\vert \ge \vert\lambda_3\vert$ 
and determine the partial recontructions,

- $\boldsymbol{T}_1 = \lambda_1\boldsymbol{v}_1\boldsymbol{v}_1^T$
- $\boldsymbol{T}_2 = \lambda_1\boldsymbol{v}_1\boldsymbol{v}_1^T + \lambda_2\boldsymbol{v}_2\boldsymbol{v}_2^T$

Finally, check that $\boldsymbol{T}_3 = \boldsymbol{T}$.

In [9]:
# possible solution
T = np.array([[7,-3,-9],[-3,-5,2],[-9,2,10]])
w, V = np.linalg.eig(T)
# look at the eigenvalues to manually sort them...
print('lambda = ', w)

lambda =  [18.14414013 -0.43436748 -5.70977265]


We can see that $\vert\lambda_1\vert > \vert\lambda_3\vert > \vert\lambda_2\vert$
and so, we can select them out in the correct order manually like this...

In [10]:
D=np.diag(w)
T1 = D[0,0]*V[:,0:1]*V[:,0:1].T       # using lambda_1
T2 = T1 + D[2,2]*V[:,2:3]*V[:,2:3].T  # using lambda_2
T3 = T2 + D[1,1]*V[:,1:2]*V[:,1:2].T  # using lambda_3
print('T1 = \n', T1)
print('T2 = \n', T2)
print('T-T3 = \n', T-T3)

T1 = 
 [[ 7.55329941 -1.7372557  -8.77369555]
 [-1.7372557   0.39956808  2.0179463 ]
 [-8.77369555  2.0179463  10.19127264]]
T2 = 
 [[ 7.22886142 -3.05895812 -8.79129842]
 [-3.05895812 -4.98481151  1.94623536]
 [-8.79129842  1.94623536 10.19031757]]
T-T3 = 
 [[-4.44089210e-15  2.66453526e-15  7.10542736e-15]
 [ 2.66453526e-15  8.88178420e-16 -8.88178420e-16]
 [ 7.10542736e-15 -8.88178420e-16 -8.88178420e-15]]


## Implication: approximation of matrices

This is quite a big deal, it means in effect that we can break a square
symmetric matrix into pieces and consider as many or as few of those
pieces as we wish.

This point of view really suggests an approximation scheme.
If $\boldsymbol{A}$ is $n\times n$ symmetric then

$$
\boldsymbol{A} =
\sum_{k=1}^n
\lambda_k\boldsymbol{v}_k\boldsymbol{v}_k^T
\qquad\text{ which suggests that }\qquad
\boldsymbol{A} \approx
\sum_{k=1}^m
\lambda_k\boldsymbol{v}_k\boldsymbol{v}_k^T
$$

for $m < n$. We would want to sort the eigenvalues so that the
most dominant ones come first in this sum, which is the same saying

$$
\vert\lambda_1\vert \ge
\vert\lambda_2\vert \ge
\vert\lambda_3\vert \ge  \cdots
$$

And this is exactly what we did above.

We'll look more closely at this in the workshop session. And,
we'll also see a related demonstration of this idea later for an example in
image compression.

### Exercise

1. If $\boldsymbol{A}$ is $n\times n$ symmetric then how many independent
quantities does it contain?

2. If we approximate 
$$
\boldsymbol{A} =
\sum_{k=1}^n
\lambda_k\boldsymbol{v}_k\boldsymbol{v}_k^T
\qquad\text{ by }\qquad
\boldsymbol{A} \approx
\sum_{k=1}^m
\lambda_k\boldsymbol{v}_k\boldsymbol{v}_k^T
$$
for some $k<$n, then how many independent quantities does this expression contain?

3. What is the ratio of approximate size to exact size?

4. Evaluate that ratio when $m=5$ and $n=1000$

#### Possible Solution

1. There are $n^2$ entries in the matrix but those under the diagonal 
are replicated above the diagonal. Hence, by adding the length of
the diagonal to the first, and then second, and then third, ...,
super-diagonals there are
$$
n+(n-1) + (n-2) + \cdots + 2 + 1 = \frac{(n+1)n}{2}
$$
2. $\boldsymbol{v}_k$ has $n$ entries, and $\lambda_k$ is just one number.
Hence this expression has just $m(n+1)$.

3. The ratio is therefore

$$
m(n+1)\div\frac{n(n+1)}{2}
= 
\frac{2m(n+1)}{n(n+1)}
= 
\frac{2m}{n}
$$

4. $m=5$ and $n=1000$ gives the ratio
$\displaystyle\frac{2m}{n}=\frac{2\times 5}{1000} = 1\%$

This example shows that if a large matrix can be well approximated by just a few 
terms in the eigen-expansion then the amoint of storage required in computer
memory can be vastly reduced.

This is very useful. But it only applies to symmetric square matrices.
We can extend it to non-symmetric matrices by introducing complex
numbers but we can't extend this to non-square matrices because they
don't have eigenvalues.

Fortunately, there is another - even more powerful - tool at our
disposal.

# Formulae

For $\boldsymbol{B}\in\mathbb{R}^{m\times n}$

$$
\boldsymbol{B} = \boldsymbol{U}\boldsymbol{\Sigma}\boldsymbol{V}^T
=\sum_{j=1}^{p} \sigma_j \boldsymbol{u}_j\boldsymbol{v}_j^T
$$

where: $\boldsymbol{U}\in\mathbb{R}^{m\times m}$,
$\boldsymbol{\Sigma}\in\mathbb{R}^{m\times n}$, $\boldsymbol{V}\in\mathbb{R}^{n\times n}$
and $p=\min\{m,n\}$. Note that $\boldsymbol{\Sigma}=\text{diag}(\sigma_1,\ldots,\sigma_p)$
and we can always arrange this so that $0 \le \sigma_1\le\cdots\le\sigma_p$.

$\boldsymbol{B}$ is real here, then $\boldsymbol{U}$ and $\boldsymbol{V}$
are real and *orthogonal*.

If $\sigma_r\ne 0$ and $\sigma_p= 0$ for all $p>r$ then
$r$ is the rank of $\boldsymbol{B}$.

Note storage for $\boldsymbol{B}$ is $mn$. That for the SVD is 
$r(m+n+1)$. The ratio is

$$
\frac{r(m+n+1)}{mn} 
= \frac{r}{n}
+ \frac{r}{m} 
+ \frac{r}{mn} 
$$

**BEWARE** that python indices start at zero. 

## The Thin SVD

Here we still have $\boldsymbol{B}\in\mathbb{R}^{m\times n}$ but with

$$
\boldsymbol{B} = \boldsymbol{U}_1\boldsymbol{\Sigma}_1\boldsymbol{V}^T
=\sum_{j=1}^{n} \sigma_j \boldsymbol{u}_j\boldsymbol{v}_j^T
$$

where: $\boldsymbol{U}_1\in\mathbb{R}^{m\times n}$,
$\boldsymbol{\Sigma}_1\in\mathbb{R}^{n\times n}$. This is called the *thin SVD*.



## SVD: The Singular Value Decomposition

The other two formulae calls are verified with the Golub, Van Loan book.

Only square matrices have eigenvalues, and not all square matrices are
diagonalizable via the similarity transform. For general matrices
containing real numbers there is a tool called the **SVD** - the
*Singular Value Decomposition*.

Let $\boldsymbol{K}$ be an $n$-row by $m$-column matrix of real numbers.
Then
$\boldsymbol{K} = \boldsymbol{U}\boldsymbol{\Sigma}\boldsymbol{V}^T$ -
this is called the *Singular Value Decomposition* of $\boldsymbol{K}$.
In this:

-   $\boldsymbol{U}$ is an $n\times n$ *orthogonal square* matrix
-   $\boldsymbol{\Sigma}$ is an $n\times m$ *rectangular diagonal*
    matrix
-   $\boldsymbol{V}^T$ is an $m\times m$ *orthogonal square* matrix

The entries on the diagonal of $\boldsymbol{\Sigma}$ are called the
*singular values* of $\boldsymbol{K}$ and the number of non-zero
singular values gives the rank of $\boldsymbol{K}$.

The columns of $\boldsymbol{U}$ (resp. $\boldsymbol{V}$) are called the
left (resp. right) singular vectors of $\boldsymbol{K}$.

Let's see an example of
$\boldsymbol{K} = \boldsymbol{U}\boldsymbol{\Sigma}\boldsymbol{V}^T$.

$$
\text{If }
\boldsymbol{K}=\left(\begin{array}{rrr}
1  &  2 & 5 \\
5  & -6 & 1 \\
\end{array}\right)
\text{ then }
\boldsymbol{U}=\left(\begin{array}{rr}
  -0.06213\ldots  & 0.99806\ldots \\
   0.99806\ldots  & 0.06213\ldots \\
\end{array}\right),
$$ $$
\boldsymbol{\Sigma}=\left(\begin{array}{rrr}
7.88191\ldots &                 0 & 0 \\
0                 & 5.46584\ldots & 0 \\
\end{array}\right)
\text{ and }
\boldsymbol{V}=\left(\begin{array}{rrr}
 0.62525\ldots & 0.23944\ldots &-0.74278\ldots \\
-0.77553\ldots & 0.29699\ldots &-0.55708\ldots \\
 0.08720\ldots & 0.92437\ldots & 0.37139\ldots \\
\end{array}\right)
$$

If we use these we can indeed check that


\begin{align}
&\left(\begin{array}{rr}
  -0.062\ldots  & 0.998\ldots \\
   0.998\ldots  & 0.062\ldots \\
\end{array}\right)
\left(\begin{array}{rrr}
7.881\ldots &                 0 & 0 \\
0                 & 5.465\ldots & 0 \\
\end{array}\right)
\left(\begin{array}{rrr}
 0.625\ldots & 0.239\ldots &-0.742\ldots \\
-0.775\ldots & 0.296\ldots &-0.557\ldots \\
 0.087\ldots & 0.924\ldots & 0.371\ldots \\
\end{array}\right)^T
\\
&\qquad{} =
\left(\begin{array}{rrr}
1  &  2 & 5 \\
5  & -6 & 1 \\
\end{array}\right)
\end{align}

as required. We aren't going to do it by hand though, that's what
computers are for!

There is a great deal that can be said about the SVD, but we're going to
stay narrowly focussed and explore its value in data science and machine
learning.

``` bash
K =

     1     2     5
     5    -6     1

>> [U, S, V] = svd(K)

U =

  -0.062137441556329   0.998067602097590
   0.998067602097590   0.062137441556329


S =

   7.881910650127741                   0                   0
                   0   5.465847098428834                   0


V =

   0.625254559166026   0.239442265089237  -0.742781352708207
  -0.775532832968505   0.296991577997824  -0.557086014531156
   0.087209868879293   0.924371897175211   0.371390676354104

>> K=U*S*V'

K =

   1.000000000000000   2.000000000000000   5.000000000000000
   5.000000000000000  -6.000000000000001   1.000000000000000
```

Let's start with the following observation. If we denote the $n$-th
column of $\boldsymbol{U}$ by $\boldsymbol{u}_n$, and the $n$-th column
of $\boldsymbol{V}$ by $\boldsymbol{v}_n$, then the statement
$\boldsymbol{K} = \boldsymbol{U}\boldsymbol{\Sigma}\boldsymbol{V}^T$
becomes (we saw something very similar to this above with eigenvalues),

$$
\boldsymbol{K}
=
(\boldsymbol{u}_1\ \boldsymbol{u}_2\ \cdots\ \boldsymbol{u}_n)
\left(\begin{array}{rrrr}
\sigma_1 & & & \\
 & \sigma_2 & & \\
 & & \ddots & \\
 & & & \sigma_n
\end{array}\right)
\left(\begin{array}{r}
\boldsymbol{v}_1^T \\
\boldsymbol{v}_2^T \\
\vdots\  \\
\boldsymbol{v}_n^T \\
\end{array}\right)
=
(\boldsymbol{u}_1\ \boldsymbol{u}_2\ \cdots\ \boldsymbol{u}_n)
\left(\begin{array}{r}
\sigma_1\boldsymbol{v}_1^T \\
\sigma_2\boldsymbol{v}_2^T \\
\vdots\  \\
\sigma_n\boldsymbol{v}_n^T \\
\end{array}\right)
$$

(we haven't shown all the zero elements of $\boldsymbol{\Sigma}$).
Simplifying this further then gives,

$$
\boldsymbol{K}
=
\sigma_1\boldsymbol{u}_1\boldsymbol{v}_1^T
+ \sigma_2\boldsymbol{u}_2\boldsymbol{v}_2^T
+ \cdots
+ \sigma_n\boldsymbol{u}_n\boldsymbol{v}_n^T
$$

> **THINK ABOUT**: $\boldsymbol{u}\boldsymbol{v}^T$ is a rank 1 matrix -
> why?

## Approximating Big Non-Square Matrices with Smaller????? Ones

``` bash
>> disp('from math-deep.pdf')
from mhttps://www.cis.upenn.edu/~jean/math-deep.pdf

>> A = [10 7 8 7;
7 5 6 5;
8 6 10 9;
7 5 9 10]

A =

    10     7     8     7
     7     5     6     5
     8     6    10     9
     7     5     9    10

>> [V D] = eig(A)

V =

    0.5016   -0.3017    0.6149    0.5286
   -0.8304    0.0933    0.3963    0.3803
    0.2086    0.7603   -0.2716    0.5520
   -0.1237   -0.5676   -0.6254    0.5209


D =

    0.0102         0         0         0
         0    0.8431         0         0
         0         0    3.8581         0
         0         0         0   30.2887

>> V*V'

ans =

    1.0000    0.0000   -0.0000   -0.0000
    0.0000    1.0000    0.0000   -0.0000
   -0.0000    0.0000    1.0000    0.0000
   -0.0000   -0.0000    0.0000    1.0000

>> A-V*D*V'

ans =

   1.0e-14 *

   -0.3553   -0.2665   -0.5329   -0.1776
   -0.2665         0         0   -0.0888
   -0.5329         0         0   -0.1776
         0         0   -0.1776         0

>> L=zeros(4,4); L(4,4)=D(4,4)

L =

         0         0         0         0
         0         0         0         0
         0         0         0         0
         0         0         0   30.2887

>> (A-V*L*V')./A

ans =

    0.1538    0.1303   -0.1046   -0.1914
    0.1303    0.1241   -0.0595   -0.2000
   -0.1046   -0.0595    0.0772    0.0324
   -0.1914   -0.2000    0.0324    0.1781

>> L=zeros(4,4); L(4,4)=D(4,4); L(3,3)=D(3,3);
>> (A-V*L*V')./A

ans =

    0.0079   -0.0040   -0.0240    0.0205
   -0.0040    0.0029    0.0097   -0.0087
   -0.0240    0.0097    0.0488   -0.0405
    0.0205   -0.0087   -0.0405    0.0272
```

...

# Fact Sheet

Look at review on CombinedNotes.pdf

# Learning Outcomes

After studying these notes you should be able to confidently:

-   Add and subtract vectors and matrices of compatible dimension.

-   Transpose a matrix, and recognise a square matrix.

-   Compute the scalar product of vectors, and product of matrices when
    they exist.

-   

CNTRL-OPTION-CLICK switch focus without raising

Select finder and merge all windows.

# THIS COPIED FROM VECTORS.IPYNB NEEDS UPDATING

## Review

We have just come a long way:

- we reviewed the mathematical notion of a *vector*.
- we saw how using `numpy` in `python` we could
  - create vectors;
  - add and subtract them, and multiply by a scalar;
  - compute various vector norms and phoney norms.

Furthermore

- we saw how to access the *toy datasets* in `seaborn`.
- how to work with `pandas` data frames.
- how to extract data frame values.
- how to represent a data point as a vector of features.

We will be building extensively on these skills in the coming weeks.

Taking raw data and manipulating it so that it is in a fomr suitable
for analysis is often referred to as **Data Wrangling**. The `pandas`
cheat sheet here <https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf> 
gives lots of examples of how to work with data frames.

For now we finish off with a look at a few more of the *toy datasets*
that `seaborn` provides. They are called *toy* because they are 
realistic enough to use when learning techniques and tools in
data science, but also small enough to get answers in real time.



## Exercises

For ...:

1. Do...
2. Do...

```
1: code goes here
2: code goes here
```

### Workshop Exercise

Based originally on
<https://stackoverflow.com/questions/8092920/sort-eigenvalues-and-associated-eigenvectors-after-using-numpy-linalg-eig-in-pyt>

- How can we use code to re-order the eigenvalues in `w` so that their absolute values are in descending order?
- How can we use that re-ordering to correctly re-order the eigenvectors that are in the columns of V?


In [11]:
print('V = \n', V)
print('    w  = ', w)
print('abs(w) = ', abs(w))

print('abs(w).argsort()           = ', abs(w).argsort())
print('np.flip( abs(w).argsort()) = ', np.flip( abs(w).argsort()))
print('abs(w).argsort()[::-1]     = ', abs(w).argsort()[::-1])
indx = np.flip( abs(w).argsort() )   
print('indx = ', indx)


V = 
 [[ 0.64520861 -0.72586798 -0.23837266]
 [-0.14839771  0.18699442 -0.97108764]
 [-0.74945578 -0.66192806 -0.01293327]]
    w  =  [18.14414013 -0.43436748 -5.70977265]
abs(w) =  [18.14414013  0.43436748  5.70977265]
abs(w).argsort()           =  [1 2 0]
np.flip( abs(w).argsort()) =  [0 2 1]
abs(w).argsort()[::-1]     =  [0 2 1]
indx =  [0 2 1]


In [12]:
w = w[indx]
V = V[:,indx]
print('lambda = ', w)
print('V = \n', V)

lambda =  [18.14414013 -5.70977265 -0.43436748]
V = 
 [[ 0.64520861 -0.23837266 -0.72586798]
 [-0.14839771 -0.97108764  0.18699442]
 [-0.74945578 -0.01293327 -0.66192806]]



Re-visit the notes to find the eigen-decomposition of the matrix
$\boldsymbol{T}$ as given by,

$$
\boldsymbol{T} = \left(\begin{array}{rrr}
 7 & -3 & -9 \\
-3 & -5 &  2 \\
-9 &  2 & 10
\end{array}\right)
$$

Use code, as descibed above, to order the eigenvalues so that 
$\vert\lambda_1\vert \ge \vert\lambda_2\vert \ge \vert\lambda_3\vert$ 
and determine the partial recontructions,

- $\boldsymbol{T}_1 = \lambda_1\boldsymbol{v}_1\boldsymbol{v}_1^T$
- $\boldsymbol{T}_2 = \lambda_1\boldsymbol{v}_1\boldsymbol{v}_1^T + \lambda_2\boldsymbol{v}_2\boldsymbol{v}_2^T$

Finally, check that $\boldsymbol{T}_3 = \boldsymbol{T}$.

In [13]:
T = np.array([[7,-3,-9],[-3,-5,2],[-9,2,10]])
w, V = np.linalg.eig(T)
indx = np.flip( abs(w).argsort() )   
w = w[indx]
V = V[:,indx]
D=np.diag(w)
T1 = D[0,0]*V[:,0:1]*V[:,0:1].T
T2 = T1 + D[1,1]*V[:,1:2]*V[:,1:2].T
T3 = T2 + D[2,2]*V[:,2:3]*V[:,2:3].T
print('T1 = \n', T1)
print('T2 = \n', T2)
print('T-T3 = \n', T-T3)

T1 = 
 [[ 7.55329941 -1.7372557  -8.77369555]
 [-1.7372557   0.39956808  2.0179463 ]
 [-8.77369555  2.0179463  10.19127264]]
T2 = 
 [[ 7.22886142 -3.05895812 -8.79129842]
 [-3.05895812 -4.98481151  1.94623536]
 [-8.79129842  1.94623536 10.19031757]]
T-T3 = 
 [[-4.44089210e-15  2.66453526e-15  7.10542736e-15]
 [ 2.66453526e-15  8.88178420e-16 -8.88178420e-16]
 [ 7.10542736e-15 -8.88178420e-16 -8.88178420e-15]]


This point of view really suggests an approximation scheme.
If $\boldsymbol{A}$ is $n\times n$ symmetric then

$$
\boldsymbol{A} =
\sum_{k=1}^n
\lambda_k\boldsymbol{v}_k\boldsymbol{v}_k^T
\qquad\text{ suggesting }\qquad
\boldsymbol{A} \approx
\sum_{k=1}^m
\lambda_k\boldsymbol{v}_k\boldsymbol{v}_k^T
$$

for $m < n$. We would want to sort the eigenvalues so that the
most dominant ones come first in this sum, which is the same saying

$$
\vert\lambda_1\vert \ge
\vert\lambda_2\vert \ge
\vert\lambda_3\vert \ge  \cdots
$$

And this is exactly what we did above.

Let's see how that might work.

In [14]:
A = np.array([[3,-2,4],[-2,6,2],[4,2,5]])
w, V = np.linalg.eig(A)
indx = np.flip( abs(w).argsort() )   
w = w[indx]
V = V[:,indx]
D=np.diag(w)
print('w = ', w)
E = np.zeros(A.shape)
for i in range(0,3):
    E = E + D[i,i]*np.matmul(V[:,i:i+1],V[:,i:i+1].T)
    print('E=\n',E)
    print('(A-E)/A', (A-E)/A)
    print('max{ (A-E)/A }', np.max( (A-E)/A) )

w =  [ 8.21699057  7.         -1.21699057]
E=
 [[2.24159712 1.12079856 3.48399703]
 [1.12079856 0.56039928 1.74199852]
 [3.48399703 1.74199852 5.41499417]]
(A-E)/A [[ 0.25280096  1.56039928  0.12900074]
 [ 1.56039928  0.90660012  0.12900074]
 [ 0.12900074  0.12900074 -0.08299883]]
max{ (A-E)/A } 1.5603992792021621
E=
 [[ 3.64159712 -1.67920144  3.48399703]
 [-1.67920144  6.16039928  1.74199852]
 [ 3.48399703  1.74199852  5.41499417]]
(A-E)/A [[-0.21386571  0.16039928  0.12900074]
 [ 0.16039928 -0.02673321  0.12900074]
 [ 0.12900074  0.12900074 -0.08299883]]
max{ (A-E)/A } 0.16039927920216146
E=
 [[ 3. -2.  4.]
 [-2.  6.  2.]
 [ 4.  2.  5.]]
(A-E)/A [[-1.62832710e-15 -1.33226763e-15 -8.88178420e-16]
 [-1.33226763e-15  4.44089210e-16  2.22044605e-16]
 [-8.88178420e-16  2.22044605e-16  1.77635684e-16]]
max{ (A-E)/A } 4.440892098500626e-16


# Technical Notes

This originated from
<https://stackoverflow.com/questions/38540326/save-html-of-a-jupyter-notebook-from-within-the-notebook>

These lines create a back up of the notebook. They can be ignored.

At some point this is better as a bash script outside of the notebook


In [15]:
%%bash
NBROOTNAME='7_decomp'
OUTPUTTING=1

if [ $OUTPUTTING -eq 1 ]; then
  jupyter nbconvert --to html $NBROOTNAME.ipynb
  cp $NBROOTNAME.html ../backups/$(date +"%m_%d_%Y-%H%M%S")_$NBROOTNAME.html
  mv -f $NBROOTNAME.html ./formats/html/

  jupyter nbconvert --to pdf $NBROOTNAME.ipynb
  cp $NBROOTNAME.pdf ../backups/$(date +"%m_%d_%Y-%H%M%S")_$NBROOTNAME.pdf
  mv -f $NBROOTNAME.pdf ./formats/pdf/

  jupyter nbconvert --to script $NBROOTNAME.ipynb
  cp $NBROOTNAME.py ../backups/$(date +"%m_%d_%Y-%H%M%S")_$NBROOTNAME.py
  mv -f $NBROOTNAME.py ./formats/py/
else
  echo 'Not Generating html, pdf and py output versions'
fi

[NbConvertApp] Converting notebook 7_decomp.ipynb to html
[NbConvertApp] Writing 661014 bytes to 7_decomp.html
[NbConvertApp] Converting notebook 7_decomp.ipynb to pdf
[NbConvertApp] Writing 81339 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', 'notebook.tex', '-quiet']
[NbConvertApp] Running bibtex 1 time: ['bibtex', 'notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 119625 bytes to 7_decomp.pdf
[NbConvertApp] Converting notebook 7_decomp.ipynb to script
[NbConvertApp] Writing 34162 bytes to 7_decomp.py
